### ISSUE TITLE
API: Develop an API for homomorphisms and isomorphisms between magmas

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#114]
In exact analogy to how Mathlib supports additive homomorphisms (`AddHom`) `φ: G →+ H` between `(G:Type) [Add G]` and `(H:Type) [Add H]`, and multiplicative homomorphisms (`MulHom`) `φ: G →* H` between `(G:Type) [Mul G]` and `(H:Type) [Mul H]`, expand `Magma.lean` to support magma homomorphisms (`MagmaHom`) `φ: G →∘ H` between `(G:Type) [Magma G]` and `(H:Type) [Magma H]`, with all the basic API copied over from Mathlib.  Similarly create support for `MagmaEquiv` analogously to `AddEquiv` and `MulEquiv`. This will help support #104 and #36.

**Comment by madvorak** [comment]
claim

**Comment by madvorak** [comment]
https://github.com/teorth/equational_theories/pull/158

**Comment by madvorak** [comment]
propose PR #158
