### ISSUE TITLE
API: Make FreeMagma a Magma

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#119]
Amusingly, the `FreeMagma` class in https://github.com/teorth/equational_theories/blob/main/equational_theories/FreeMagma.lean does not currently have a `Magma` instance.  Let's give it one.  (This means that a `FreeMagma` will have both a `*` operation and an (identical) `∘` operation, but I see little harm in having this redundancy.)

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose pr #121

**Comment by Command-Master** [comment]
propose PR #121
