### ISSUE TITLE
SUBGRAPH: Show that 14 implies 29

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#120]
This is the dual of the existing implication that 29 implies 14, and should be easy to add.  When done, one can update the `\lean{}` tag of `Theorem \ref{29_equiv_14}` in https://github.com/teorth/equational_theories/blob/main/blueprint/src/chapter/implications.tex , and also add a \leanok to the proof to finish it off.

**Comment by shetzl** [comment]
claim

**Comment by shetzl** [comment]
propose PR #128
