### ISSUE TITLE
INFINITE: State and prove Theorem 2.36 (second Kisielewicz law) of the blueprint in Lean.

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#125]
The theorem is at https://teorth.github.io/equational_theories/blueprint/subgraph-eq.html#kis-thm2 .  The proof should be similar to that of https://teorth.github.io/equational_theories/blueprint/subgraph-eq.html#kis-thm , and can be placed in the same file [`InfModel.lean`](https://github.com/teorth/equational_theories/blob/main/equational_theories/InfModel.lean).

When done, a \leanok can be added to the statement and proof of the theorem in the blueprint.

**Comment by teorth** [comment]
Oops, you are right.  Since you are working on the task anyway, please include the relevant corrections to the blueprint and lean files in your PR!

Also, to claim, you need to make a comment containing only the word "claim", as per https://github.com/teorth/equational_theories/blob/main/CONTRIBUTING.md .  (If the instructions there were confusing, let us know and we will try to make them clearer.)

**Comment by jscanvic** [comment]
claim

**Comment by jscanvic** [comment]
propose PR 202

**Comment by jscanvic** [comment]
withdraw PR #202

**Comment by jscanvic** [comment]
propose PR #202
