### ISSUE TITLE
METATHEOREM: Formalize and prove Theorem 3.8, giving a necessary condition for implication

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#131]
This would likely go in a new Lean file (for metatheorems?).  The theorem asserts that if a law has the property that each variable occurs the same number of times on each side, then it can only imply other laws with the same property.  The proof involves testing the law on a characteristic zero field, such as the reals with the addition law.  

It requires setting up some API for counting how often a variable occurs on the LHS and RHS of a law.  It will also require #132 to be completed.

When done, update the blueprint of Theorem 3.8 by adding a \leanok to the statement and proof of the theorem.

**Comment by codyroux** [comment]
Neat! Sure looks a lot like the little test metatheorem I proved, which I will PR first.

**Comment by codyroux** [comment]
claim

**Comment by codyroux** [comment]
Ooops, the proof I had in mind is completely different from the blueprint one, sorry.

**Comment by codyroux** [comment]
unclaim

**Comment by codyroux** [comment]
Ok, now that I've thought about it:

I can probably prove this without too much hassle, but only if the magma is `Multiset` (equipped with union), rather than `ℝ`. I can change the proof afterwards. Is that ok?

**Comment by codyroux** [comment]
I have a partial proof, here: https://github.com/codyroux/equational_theories/blob/free-comm/equational_theories/FreeComm.lean

But it needs to be fixed, and I'm late for work, so I'll leave this on the table.

**Comment by codyroux** [comment]
Ok the excellent @fpvandoorn (of mechanized CH independence fame) helped me solve this.

propose PR #177
