### ISSUE TITLE
API: Give MagmaLaw the structure of a Preorder (Lemma 3.2)

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#132]
Thus, if `E`, `E'` are laws, then `E ≥ E'` will be true precisely when `E` implies `E'`, that is to say every magma that obeys `E` obeys `E'`.  The axioms of a preorder will need to be verified.

When done, mark Lemma 3.2 in the blueprint with a \leanok in both the statement and proof.

**Comment by goens** [comment]
claim

**Comment by goens** [comment]
propose PR#135

**Comment by goens** [comment]
awaiting-review
