### ISSUE TITLE
API: Show that the free magma has the universal property (Definition 1.4)

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#133]
Given a map `f : α -> G`, show that `evalInMagma f` is the unique magma homomorphism that extends `f`.  (This requires that #114 is completed.  Additionally, `evalInMagma f` should now have the type `MagmaHom`.)

Similarly, if `f : α → β`, show that `fmapFreeMagma f` is the unique magma homomorphism that extends `f`.  (One can add some API relating these two operations as necessary.)

When done, mark Definition 1.4 with a \leanok on the blueprint.

**Comment by franklindyer** [comment]
claim
