### ISSUE TITLE
COUNTING: Count words of order n in the free magma (Lemma 1.3)

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#134]
This requires importing Catalan numbers https://leanprover-community.github.io/mathlib4_docs/Mathlib/Combinatorics/Enumerative/Catalan.html from Mathlib.  While not directly used in the other counting results in this chapter of the blueprint, this would be good practice for using Catalan numbers, which appear in many other of the counting tasks.

When done, mark the statement and proof of Lemma 1.3 with a \leanok in the blueprint.

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose PR #146
