### ISSUE TITLE
SUBGRAPH: Show that 1689 implies (and is in fact equivalent to) 2 (Theorem 4.5)

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#136]
This is a surprisingly tricky implication.  In 1997, Kisielewicz obtained a computer assisted proof, whose output is as follows:

> The longest deduction my program finds is one showing (yx)((xz)z) x implies x y. It consists of 13 subreductions and it seems to me that there is no shorter way to prove this fact. Here is the corresponding part of the program's report.

> [1] (ab)((bc)c)=b 
> Subreducing [1] in [1] by subterm ab yields:
> [2] a((((ab)b)c)c)=(ab)b 
> Subreducing [1] in [1] by subterm bc yields: 
> [3] (a(bc))(c((cd)d))=bc 
> Subreducing [1] in [2] by subterm ((ab)b)c yields: 
> [4] a(b((bc)c))=(ab)b 
> Subreducing [3] in [4] by subterm a(b((bc)c)) yields: 
> [5] ((a(bc))c)c=bc 
> Subreducing [5] in [1] by subterm (bc)c yields: 
> [6] (a(b(cd)))(cd)=b(cd) 
> Subreducing [6] in [5] by subterm (a(bc))c yields: 
> [7] (a(bc))(bc)=a(bc) 
> Subreducing [1] in [5] by subterm bc yields: 
> [8] ((ab)((bc)c))((bc)c)=b 
> Subreducing [1] in [7] by subterm a(bc) yields: 
> [9] a((ab)b=a 
> Subreducing [7] in [9] by subterm (ab)b yields: 
> [10] a(a(bc))=a 
> Subreducing [8] in [9] by subterm (ab)b yields: 
> [11] (ab)b=ab 
> Subreducing [4] in [10] by subterm a(a(bc)) yields: 
> [12] (aa)a=a 
> Subreducing [12] in [1] by subterm (bc)c yields: 
> [13] (ab)b=b 
> Subreducing [11] in [13] by subterm (ab)b yields: 
> [14] ab=b Whence, a=b.

This claim (currently a conjecture in Subgraph.lean) would be a prime target for automated proving tools.

When done, mark the statement and proof of Theorem 4.5 with a \leanok in the blueprint.

**Comment by ChienYungChi** [comment]
claim

**Comment by ChienYungChi** [comment]
propose PR #154
