### ISSUE TITLE
DATA: Add a MagmaLaw associated to each equation in Equations.lean or AllEquations.lean

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#143]
For each EquationX `abbrev` in Equations.lean, also add a `LawX` that defines the corresponding element of `MagmaLaw`. (EDIT: this step will no longer be necessary if #290 is completed.)

Modify the `equation` elaborator in EquationCommand.lean to do something similar for AllEquations.lean.

This is the first step towards transitioning from having equations as the ground truth of the universe of assertions, to laws.

**Comment by goens** [comment]
claim

**Comment by goens** [comment]
propose PR #357

**Comment by 0art0** [comment]
Apologies for the overlap, my PR #356 also does something similar, as a path towards proving non-implications using meta-theorems. I'd be happy to close my PR and make the code depend on your PR.
