### ISSUE TITLE
METATHEOREM: non-trivial implications preserve size

### ISSUE THREAD

**Issue by codyroux** [teorth/equational_theories#156]
Formalize and prove the following meta-theorem:

Any implication of a set of equalities whose left and right hand orders are greater than `n` must either be of the form `w = w` or of the form `w = w'` with both sides being of order at least `n`.

**Comment by codyroux** [comment]
claim

**Comment by 0art0** [comment]
Hernan and I will update the blueprint shortly with a more general version of this meta-theorem.

**Comment by codyroux** [comment]
propose PR #152

**Comment by codyroux** [comment]
@0art0  Not sure whether this means I should update the statement and proof, or withdraw altogether?

**Comment by 0art0** [comment]
Apologies for being vague, I think it's fine as it is. We still need some more time to look at where the generalized metatheorem would sit among the various things formalized so far, or whether it even needs to be formalized explicitly. For reference, this is a part of what we plan to include in the blueprint: https://github.com/0art0/equational_theories/blob/invariant-based-metatheorem-blueprint/blueprint/src/chapter/lifting_magmas.tex.

**Comment by codyroux** [comment]
(that link above is currently 404)

**Comment by codyroux** [comment]
withdraw PR #152

**Comment by codyroux** [comment]
propose PR #233

**Comment by codyroux** [comment]
(Already merged)
