### ISSUE TITLE
Names for universally-quantified elements

### ISSUE THREAD

**Issue by madvorak** [teorth/equational_theories#170]
I generally like the way we name the universally-quantified elements, but I don't think that `x y z w u v` is the best order.

**Comment by teorth** [comment]
Do you have an alternate proposal? Note there is the remote possibility that we may occasionally need seven or more variables.

**Comment by madvorak** [comment]
I would go anti-alphabetically after reaching the end of the alphabet:
`x y z w v u`

**Comment by teorth** [comment]
Fair enough.  I have created a poll for this issue: https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/POLL.3A.20Names.20of.20universally.20quantified.20variables

**Comment by teorth** [comment]
Closed due to lack of consensus, however the issue can be revived if someone is willing to do the refactor by making a proposal at  https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/POLL.3A.20Names.20of.20universally.20quantified.20variables
