### ISSUE TITLE
FRONTEND: Generate a text file of all unresolved implications, quotiented out by known equivalences

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#173]
Thus, every equation should be replaced by the equation with the lowest number that is known to be equivalent to the original equation.

When done, select a permanent location for that file, and link to it in README.md.  Eventually, this file should be regularly regenerated, perhaps as part of #171.

**Comment by teorth** [comment]
This is essentially already in https://github.com/amirlb/equational_theories/tree/unknown-implications so I guess the main task is to integrate it into the CI in #171

**Comment by Command-Master** [comment]
Alternatively this could be edited to the transitive closure code, as it already computes the equivalence classes so it should be trivial to output it

**Comment by amirlb** [comment]
Definitely, my plan was to clean up the Python logic while moving it to Lean, all the ingredients already exist. If you want to take this you're welcome.

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
How should it treat conjectures? I guess there could be a command line flag to choose whether to consider them

**Comment by amirlb** [comment]
There are some tricky parts there (which way is stronger implications and which is weaker? etc), you can use
https://github.com/teorth/equational_theories/pull/144
as a reference for these.

**Comment by amirlb** [comment]
> How should it treat conjectures? I guess there could be a command line flag to choose whether to consider them

Makes sense to have a command line flag.

For this script I guess the default should be to include them, since people will want to use it to find genuinely unexplored territory.

**Comment by Command-Master** [comment]
propose PR #176
