### ISSUE TITLE
INFINITE: State and prove Theorem 2.37 (Equation 5105 has no non-trivial finite models) in Lean

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#181]
The result can be found at https://teorth.github.io/equational_theories/blueprint/subgraph-eq.html#5105-nontrivial

The proof would be similar to the first part of https://teorth.github.io/equational_theories/blueprint/subgraph-eq.html#kis-thm , and go into InfModel.lean.

When done, update the blueprint accordingly with a \leanok for both the statement and proof.

**Comment by JoseBrox** [comment]
Perhaps I'm mistaken, but if $x=y(y(y(xu)))$ (5105b) for all $x,y,u$ then $yx = y(y(y(y(xu)))) = y$ (by taking $x\to y, u\to xu$ in (5105b)) for all $x,y$, hence $x=y(\cdots) = y$ for all $x,y$; so, isn't (5105) equivalent to the singleton law?

**Comment by teorth** [comment]
Oops, the proof I had was not correct (I misunderstood the source material).  I uploaded a hopefully more correct proof.  (This is one reason why we formalize these things!)

**Comment by ChienYungChi** [comment]
claim

**Comment by ChienYungChi** [comment]
propose PR #195
