### ISSUE TITLE
TYPE: Show that semantic entailment for Type * is equivalent to semantic entailment for Type

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#186]
This is a technical request, inspired by a comment at #36.  It could be useful to have some way within Lean to show that the assertions

``theorem (G: Type *) [Magma G] (h: EquationX G): EquationY G`

and

theorem (G: Type) [Magma G] (h: EquationX G): EquationY G`

are equivalent to each other (or to `LawX` implying `LawY`).  Similarly for the counterexamples to such implications.  This type reduction should be achievable through the completeness theorem.

**Comment by codyroux** [comment]
claim

**Comment by codyroux** [comment]
I am sadly defeated by the universe handling in Lean.

**Comment by codyroux** [comment]
disclaim

**Comment by teorth** [comment]
Completed in #458
