### ISSUE TITLE
FRONTEND: Generate a list of "equivalence-creating" implications: open implications, quotiented by equivalence, whose converse is proven or conjectured true

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#188]
As discussed in https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Dynamically.20detecting.20useful.20implications.20to.20decide , these are particularly "high-yield" implications to prove true, as each such proof reduces the number of equivalence classes of laws by one, thus potentially eliminating thousands of laws from the list of outstanding implications.  So this would be a good reduced set of equations to test more advanced automated tools against.

If there is already a regularly scheduled task to autogenerate files of implications, this additional file could be added to that scheduled task.

**Comment by amirlb** [comment]
propose PR #197
