### ISSUE TITLE
FRONTEND: A web tool that, when input an equation number, lists all equations known or conjectured to imply it, and all equations that it is known or conjectured to imply.

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#209]
The tool can also describe the equation, as well as all the equations in the lists.

As an optional expansion, list the implications involving this equation that are still open.

**Comment by carlini** [comment]
claim

**Comment by Command-Master** [comment]
Perhaps equations which both imply it and it implies should be listed separately, as equations which are equivalent to it?

**Comment by carlini** [comment]
propose PR #301
