### ISSUE TITLE
Closure.lean should mark all reflexive implications as `implicit_proof_true`

### ISSUE THREAD

**Issue by dwrensha** [teorth/equational_theories#215]
Currently reflexive implications get marked as `unknown`. As discussed [on zulip](https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/visualization.20of.20graph.20closure/near/474048852), we don't want to require explicit proofs for these. They should be marked as implicitly true.

**Comment by dwrensha** [comment]
cc @Command-Master, who wrote `Closure.lean`

**Comment by Command-Master** [comment]
propose PR #218
