### ISSUE TITLE
API: Increase priority of Magma operation, and add coercions between [Magma] and [Mul]

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#234]
See the discussion in https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Symbol.20for.20.60Magma.2Eop.60

The two tasks are:

- Set the priority for Magma.op higher than for Function.comp so that in the (rare) cases we work with magmas that also have a composition operation, `∘` defaults to the magma operation.
- Create coercion API to convert `[Magma G]` to `[Mul G]` if needed (but do not make these instances, as usually we would not want to automatically activate these coercions).

**Comment by fpvandoorn** [comment]
claim

**Comment by fpvandoorn** [comment]
propose PR #240

**Comment by fpvandoorn** [comment]
withdraw PR #240
