### ISSUE TITLE
SUBGRAPH: Show that 953 implies 2

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#236]
Proof is at https://teorth.github.io/equational_theories/blueprint/sect0003.html#953_equiv_2 based on discussion at https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Ideas.20for.20unknown.20implications (which used a slightly different proof).  This will require transferring Equation 953 from `AllEquations.lean` to `Equations.lean`.

When done, mark the statement and proof of Theorem 4.7 with `\leanok`'s and an appropriate `\lean{}` reference.

**Comment by debordle** [comment]
claim

**Comment by debordle** [comment]
propose PR #262
