### ISSUE TITLE
Transitive closure pruning the finite magmas

### ISSUE THREAD

**Issue by zaklogician** [teorth/equational_theories#265]
In `equation_theories/Generated/All4x4Tables`, we refute potential implications between equational laws by finding small finite counterexamples. These counterexamples are generated by automated tools.

Originally, the generated counterexamples were pruned using the graph of known implications (#196).

The recent addition of 5x5 cancellative magmas broke this pruning process (#224): the file format changed substantially, and the existing pruning script (`All4x4Tables/src/generate_lean.py`) cannot handle it.

Making the pruning work again could substantially speed up the checking of `All4x4Tables`, and further cut down on the number of magmas we need. This could be done by fixing the existing pruning script, or writing a new one (but see the note below regarding the former).

**Note:**

I made an attempt to naively port the script to make it compatible with the changed file format [here](https://github.com/zaklogician/equational_theories/commit/63355c23bbcbb0d9ac16951ebf27ff2dca6a6c0a). At first everything seemed to work, the proof goes through. However, inspecting the output of `lake exe extract_implications outcomes --hist` shows that we lose quite a few refutations! Unfortunately, there are many places where things could go wrong, including in the original script, one of my changes, or even in the Lean code which counts implicit proofs. As of now I have no spare capacity to look into this myself, but am happy to assist if somebody takes it up.

**Comment by teorth** [comment]
Is this task now completed, or should the issue remain open?

**Comment by zaklogician** [comment]
This was resolved by #275 .
