### ISSUE TITLE
CENTRAL_GROUPOID: Resolve all remaining implications of the form 168 => X

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#266]
Only 42 implications of the form Equation 168 => Equation X remain open.  Equation 168 is the equation of a central groupoid.  The discussion in Section 5 of Knuth's paper https://www.sciencedirect.com/science/article/pii/S0021980070800321?ref=cra_js_challenge&fr=RR-1 appears to resolve many of these, as does his examples of "non-natural central groupoids", such as those in Section 7 of Knuth, which could be added to the current lists of interesting magmas, as discussed in https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Collecting.20interesting.20finite.20magmas.

**Comment by zaklogician** [comment]
claim

**Comment by zaklogician** [comment]
Progress report. Knuth's A_2 resolves a whole bunch of these, but not quite all of them. The following 13 remain open:
3456, 3457,3511,3512,3513,3862,3877,3918,3955,3993,5105,28393,374794.

Next step: try to construct the other noncentral magmas;  if that fails for some reason, try some hand-guided generation to produce counterexamples.

**Comment by teorth** [comment]
I guess this means that A_2 also creates some additional anti-implications beyond 168=>X then?  But perhaps those were already all known.

**Comment by zaklogician** [comment]
Yes, it resolves a few non-168 implications as well. The reason there is no PR yet is that I plan to put `A_2` into SmallMagmas instead of `All4x4Tables` (where it'd just be one more multiplication table without context).

**Comment by teorth** [comment]
With the latest update, it seems from https://teorth.github.io/equational_theories/implications/?168 that we have now in fact resolved all implications (from what I can tell, all the open implications were in fact true!).

**Comment by teorth** [comment]
One can of course continue formalizing results about central groupoids, but it seems that this particular issue is in fact now resolved.

**Comment by zaklogician** [comment]
Sweet, thanks!
