### ISSUE TITLE
TOOL: Given one or more Lean files, extract the implication status of all equations appearing in the file

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#29]
Given one or more Lean files as input, extract all the implications and proof_wanted statements from that file.  Then, for any two equations i, j that appear anywhere in these implications, report the status of the implication i => j as one of the following:

- Explicitly proven.  This implication is an explicit theorem in the files.
- Implicitly proven.  This implication is not explicitly a theorem, but can be derived from the explicit theorems in the files.
- Explicitly conjectured.  This implication is not proven, but is an explicit proof_wanted in the files.
- Implicitly conjectured.  This implication is not proven or explicitly conjectured, but follows from the explicit theorems and conjectures in the files.
- Open.  The implication is not even conjectured to be true or false.
- Implicitly conjectured false.  The implication is not disproven or explicitly conjectured false, but its falsity follows from the explicit theorems and conjectures in the files.
- Explicitly conjectured false.  The negation of this implication is an explicit proof_wanted in the files, but this negation does not follow from proven theorems.
- Implicitly disproven.  The negation of this implication is not an explicit theorem in the files, but follows from these theorems.
- Explicitly disproven.  The negation of this implication is an explicit theorem in the files.

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
Should this tool be a metaprogram, or is it fine for it to shallowly parse the files (i.e. search for `(G: Type*) [Magma G] (G: Equation(\d+) G) : Equation(\d+) G` and `∃ (G: Type) (_: Magma G), Equation4512 G ∧ ¬ Equation42 G`, and add special suuport for `Equation1_true`)?

**Comment by dwrensha** [comment]
#22 demonstrates a starting point for one way to do this kind of analysis directly in Lean.

**Comment by teorth** [comment]
> Should this tool be a metaprogram, or is it fine for it to shallowly parse the files (i.e. search for `(G: Type*) [Magma G] (G: Equation(\d+) G) : Equation(\d+) G` and `∃ (G: Type) (_: Magma G), Equation(\d+) G ∧ ¬ Equation(\d+) G`, and add special suuport for `Equation1_true`)?

In the longer term I think a metaprogram would be the most robust solution (that would also be adaptable for other projects), but a "quick and dirty" shallow approach may be faster in the short term.  So it could go either way.  One compromise is to try to write a quick and dirty program, but in a way that many of the components of the code could be refactored into a more robust long-term solution later.

**Comment by Command-Master** [comment]
If #22 could be modified so `Implication` contains whether it's conjectured I could directly process the `Output` structure it produces

**Comment by Command-Master** [comment]
Isn't this already implemented in `scripts/process_implications.py`?

**Comment by teorth** [comment]
A feature request: it should be possible to specify a set of equations to restrict to, that may be smaller than the full set of equations considered by the full set of lean imports.  For instance, `Subgraph.lean` may only be interested in the equations from `Equations.lean`, but may also import some large generated files of implications that draw from the much larger `AllEquations.lean`.  Nevertheless one might only be interested in generating a table of implications from the `Equations.lean` list only.

Also, one should not assume that the full list of equations under consideration is numbered consecutively.  (There is discussion to include some selected longer equations, which under our standard numbering system, could be assigned a number far larger than 4694.)

**Comment by dwrensha** [comment]
I believe that #93 and #85 together will provide easy access to all of the data needed to support the queries described above.

**Comment by Command-Master** [comment]
> A feature request: it should be possible to specify a set of equations to restrict to, that may be smaller than the full set of equations considered by the full set of lean imports. For instance, `Subgraph.lean` may only be interested in the equations from `Equations.lean`, but may also import some large generated files of implications that draw from the much larger `AllEquations.lean`. Nevertheless one might only be interested in generating a table of implications from the `Equations.lean` list only.
> 
> Also, one should not assume that the full list of equations under consideration is numbered consecutively. (There is discussion to include some selected longer equations, which under our standard numbering system, could be assigned a number far larger than 4694.)

In these cases should it contain equations on the restricted set implied by transitivity from equations outside the set, or should it from the start only consider implications about those equations?

**Comment by teorth** [comment]
I'd say the former; we're interested in maximizing the number of implications available in the set of interest.  (In principle one could try to play some restricted game in which one is somehow "not allowed" to use certain equations, but I can't think of any scenario for our project where this would be desirable.)

**Comment by Command-Master** [comment]
Another feature I found useful in my prototype and plan to add is having "#check_closure EquationA EquationB", to output the status of implications between EquationA and EquationB

**Comment by Command-Master** [comment]
propose PR #126
