### ISSUE TITLE
REFACTOR: Make the equation definitions in Equation.lean use the `equation` elaborator from EquationsCommand.lean

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#290]
This will help standardize the introduction of equations, in particular making it easier to transfer equations from AllEquations.lean to Equations.lean.  (Also, in the future we will want to pair each equation with a law, so having it all done through the standardized `equation` elaborator will mean we do not need to do this by hand for each subgraph equation.

**Comment by Shreyas4991** [comment]
claim

**Comment by Shreyas4991** [comment]
propose PR #295

**Comment by Shreyas4991** [comment]
docstrings need to be allowed for this command before the CI is run and this PR is merged. 

See one of the Zulip threads:
1. [Thread 1]( https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Refactoring.20with.20Equation.20Command/near/474930942)
2. [Thread 2](https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/Allow.20docstring.20for.20command/near/474931821)
