### ISSUE TITLE
SUBGRAPH: Add the implications/anti-implications between 8 and the other equations as proof_wanted statements.

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#30]
Only a generating set of implications (and anti-implications) needs to be added to Subgraph.lean, of course.  Human-readable sketches of proofs can be added in comments.

**Comment by edegeltje** [comment]
claim

**Comment by edegeltje** [comment]
fwiw, it seems the implications in the graph have all been added already. i'm looking now if the non-implications are all added...

**Comment by edegeltje** [comment]
propose PR #81
