### ISSUE TITLE
SUBGRAPH: Show 40 does not imply 3, 8, 42, 43, 4512; and 4, 387, 4582 does not imply 40

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#31]
Only a generating set of implications needs to be added to Subgraph.lean, of course.
Human-readable sketches of proofs can be added in comments.

**Comment by teorth** [comment]
Added Seraphina Nix's sketch of proofs (from https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Outstanding.20tasks.2C.20v1/near/473000267) in the comments.

**Comment by ChienYungChi** [comment]
claim

**Comment by ChienYungChi** [comment]
propose PR #53
