### ISSUE TITLE
COUNTEREXAMPLE: Show that 3102 does not imply 3176, 270

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#312]
Code is provided at https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/3102.20does.20not.20imply.203176 but needs to be refactored to be consistent with the project notation.

As a possible first in a set of string-based (or technically list-based) examples (but which does not involve the equations studied in `Subgraph.lean`, one could perhaps place this proof in a separate file, e.g., `StringMagmas.lean`.

When done, add the new file to the top-level `equational_theories.lean` file, and also add a link to it in the relevant `CONTRIBUTING.md` list.

**Comment by madvorak** [comment]
claim

**Comment by madvorak** [comment]
propose PR #317
