### ISSUE TITLE
SUBGRAPH: Prove 5 does not imply 42, 43, 4513

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#32]
Only a generating set of implications needs to be added to Subgraph.lean, of course.
Human-readable sketches of proofs can be added in comments.

**Comment by teorth** [comment]
Seraphina Nix's sketch of proof is included in the comments to the Lean file.

**Comment by ChienYungChi** [comment]
claim

**Comment by ChienYungChi** [comment]
propose PR #49
