### ISSUE TITLE
FRONTEND: A web page that takes in a finite magma (in some standardized format), and returns the equations obeyed or not obeyed by this magma.

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#332]
If this submitted magma generates new anti-implications, instructions would be given on how to submit it as a PR.  (I assume permitting direct submission to the repository would be a security risk, and possibly not even technically feasible even with admin privileges.)

The web page could provide some sample finite magmas as examples to illustrate the tool.

The equations listed can be linked to their corresponding pages on https://teorth.github.io/equational_theories/implications/

**Comment by zaklogician** [comment]
cliam

**Comment by teorth** [comment]
This is great!  It can certainly go into the main repository (or stay external, depending on what you prefer).

**Comment by pitmonticone** [comment]
Thank you very much for your contributions @zaklogician, both in general and for your work on the FME in particular. 

Your proposal makes a lot of sense, and I completely agree that we should keep the FME source in this repository to maximise compatibility, maintainability, and ensure integrated future development.

In terms of organisation, at the moment we only have a `scripts` folder, which is typically reserved for independent utilities or quick tests.

It's very typical (and I would say best practice) in open-source projects to reserve the `tools` or the `libraries` (`libs` is very common) for library-, package-, or tool-level code which is exactly the case of FME. 

In this specific case I believe the best approach would be to create a `tools/FiniteMagmaExplorer` or `tools/FME` directory for the FME source, where it can function as a project-specific tool. Its compiled HTML+JS output can then be placed in the dedicated `home_page` folder, as you suggested, to integrate smoothly with the website.

**Comment by zaklogician** [comment]
propose PR #468

**Comment by pitmonticone** [comment]
I'm assisting there. I'm setting up my local env to be able to serve Jekyll sites comfortably.
