### ISSUE TITLE
COUNTEREXAMPLE: Numerically test finite field magmas with linear operations

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#346]
See https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/An.20old.20new.20idea for discussion.  Loop over small finite fields `F` (e.g., of prime order `p`), and coefficients `a` and `b` in `F`, and consider magma operations on `F` of the form `x ◇ y = a * x + b * y`.  Then all word maps are just linear forms in the variables (with coefficients computable in terms of `a`, `b`) and it will be easy to check which equations are satisfied by these examples.  Use this to create new anti-implications (for instance, this method shows that 1286 does not imply 3).

**Comment by dwrensha** [comment]
#349 is one successful instance of using this method

**Comment by carlini** [comment]
claim

**Comment by carlini** [comment]
It looks like #380 may have completed the implications that can be shown with finite linear magmas up to Z/200Z. I will double check this tomorrow.

**Comment by carlini** [comment]
propose PR #416

**Comment by teorth** [comment]
This makes sense to me.  There are only so many primes that can divide a discriminant or resolvent, and the Chebotarev density theorem tells us (especially if we assume GRH) that polynomials will split completely over many small finite fields, so I would expect with our low degree, small coefficient examples that all constructions will be detected in a finite field of order up to 200.  I guess we could try to prove a rigorous upper bound here to completely settle the matter from a theoretical standpoint; will make an issue about this.
