### ISSUE TITLE
EQUATION_EXPLORER: Allow for each equation to have a comment file (a text file in the repository) that is displayed when viewing the page for that equation

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#365]
For instance, one can use the content in https://github.com/teorth/equational_theories/wiki/Tour-of-selected-equations to seed these comments.  One could also later populate this content more automatically with other material, such as the affine schemes arising in #364.

**Comment by carlini** [comment]
claim

**Comment by carlini** [comment]
propose PR #423

**Comment by teorth** [comment]
For some reason this issue did not close automatically, but in any event it is completed.
