### ISSUE TITLE
INFINITE: Prove Theorem 3.11 (laws with at most two variables have nontrivial finite models)

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#374]
A result of Austin. Proven by considering linear models `x ◇ y = a * x + b * y`.  Some field theory may be required to formalize the proof properly.

`InfModel.lean` is the most logical place to place this theorem.

When done, mark the statement and proof of the theorem in the blueprint with `\leanok`s, and the statement with a `\lean{}` tag.

**Comment by jscanvic** [comment]
claim

**Comment by jscanvic** [comment]
propose #442
