### ISSUE TITLE
FRONTEND: Have the dashboard default to listing "core" implication statistics between the 4694 equations, but also mention "expanded" statistics

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#379]
In particular, completion percentages should be tied to the core equations.  Expanded equations can be listed lower down in the dashboard page and generally made not as prominent as the core statistics.

**Comment by teorth** [comment]
This may require first resolving #142.

**Comment by dwrensha** [comment]
claim

**Comment by dwrensha** [comment]
Addressed in #381. Currently the "expanded" statistics will not be shown in the dashboard, but adding them in the future would be straightforward if desired.

**Comment by teorth** [comment]
Essentially resolved for now.
