### ISSUE TITLE
EQUATION_EXPLORER: when displaying conjectured (anti-)implications, color them in a lighter shade of grey than proven implications

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#410]

**Comment by carlini** [comment]
claim

**Comment by carlini** [comment]
Actually I think it already does this

https://teorth.github.io/equational_theories/implications/?2126

Look at 167/168, they should be highlighted.

**Comment by teorth** [comment]
Ah, great!  One less issue to deal with, then.
