### ISSUE TITLE
CONFLUENT: Formalize and prove Theorem 9.2 (existence and uniqueness of free magmas subject to a theory)

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#412]
This is a generalization of #133 and so one may be able to adapt the code.

Of course, an initial step will be to formalize what it means to be a free magma relative to a theory in the first place (Definition 9.1).

**Comment by codyroux** [comment]
Wait isn't this exactly what we do in completeness? https://github.com/teorth/equational_theories/blob/e56c7bcc86b799cded72a3912d672fb225c9da3b/equational_theories/Completeness.lean#L118

**Comment by codyroux** [comment]
I guess not uniqueness.

**Comment by teorth** [comment]
Yes, this is very close to what we need.  It would be nice to have a predicate that asserts that a magma (together with an embedding map) is a free magma relative to a theory, because sometimes we want to work with a more concrete magma than the canonical free magma (free magma modulo equivalences), see e.g., Examples 3-6 in https://teorth.github.io/equational_theories/blueprint/abstract-nonsense-chapter.html .  These would all be isomorphic to `FreeMagmaWithLaws β Γ`, but not actually equal to that magma.

**Comment by codyroux** [comment]
If only we had univalence :)

**Comment by codyroux** [comment]
claim

**Comment by codyroux** [comment]
Propose PR #563
