### ISSUE TITLE
EQUATION_EXPLORER: Generalize the "Prove this!" link to a "Try this!" link for proven (or conjectured) implications/anti-implications

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#415]
Of course, in these cases only one of the two statements should be presented in the playground: if for instance an implication is proven, the playground should only list the implication, and similarly for anti-implications.

**Comment by carlini** [comment]
To clarify what you're thinking: every implication in the page should have a link next to it. Any one that's in the proven/(anti-) columns will have a "try this", anything on the unknown will be "prove this"?

**Comment by Command-Master** [comment]
I think conjectures should also have "prove this"

**Comment by carlini** [comment]
claim

**Comment by carlini** [comment]
propose PR #450

**Comment by carlini** [comment]
I believe this can be closed now.

**Comment by carlini** [comment]
(Am I doing something wrong with the commands that it's not closing automatically?)

**Comment by Command-Master** [comment]
I think because you did "propose PR" before it proceeded the "claim" it didn't link it to the PR

**Comment by carlini** [comment]
propose PR #450

**Comment by teorth** [comment]
Not sure why it didn't auto-close, but I will manually close it. Thanks for completing the task!

**Comment by pitmonticone** [comment]
It's an issue with unescaped special characters. I'm going to work on it soon.
