### ISSUE TITLE
EQUATION_EXPLORER: A button to download the main equation statistics page as a spreadsheet (e.g., in CSV format)

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#419]
One could also have a similar download option for the individual equation pages.

**Comment by Joe-McCann** [comment]
Would it also be worthwhile to have a CSV version of the image file? I feel like that would be easier to perform data analysis on

**Comment by Joe-McCann** [comment]
claim

**Comment by Joe-McCann** [comment]
propose https://github.com/teorth/equational_theories/pull/625

**Comment by Joe-McCann** [comment]
propose PR https://github.com/teorth/equational_theories/pull/625
