### ISSUE TITLE
EQUATION_EXPLORER: List smallest non-trivial finite magmas associated to each equation

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#443]
The data set is https://github.com/teorth/equational_theories/blob/main/data/smallest_magma.txt (see also https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Collecting.20interesting.20finite.20magmas ) that contains the size of the smallest non-trivial magma that obeys a law, if one exists of size at most 5.  This could be included in the equation page of EE: Something like "Size of smallest non-trivial magma: N" if N <= 5 is listed in the table, or
"Size of smallest non-trivial magma: N/A" otherwise.  For instance, for equation 467, the size of the smallest non-trivial magma is 5.

**Comment by zaklogician** [comment]
The smallest_magma dataset could probably be expanded (using e.g. all the data we have in All4x4Tables) to give multiplication tables instead of just numbers. Then one could link to these tables in the Finite Magma Explorer.

**Comment by teorth** [comment]
Good idea.  I made an issue for this.

**Comment by few** [comment]
claim

**Comment by few** [comment]
propose #529
