### ISSUE TITLE
ASTERIX: Show that 65 does not imply 1491

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#463]
See the blueprint chapter at https://teorth.github.io/equational_theories/blueprint/asterix-chapter.html and the discussion at https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Equation.2065.20-.3E.20left.20cancellability .  Note that the blueprint requires some correction and modification a discussed at the latter link.  

This can go in a new Lean file.  When done, update the blueprint with appropriate `\lean` and `\leanok` tags.

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose PR #513
