### ISSUE TITLE
Build performance issues from equation_command

### ISSUE THREAD

**Issue by Shreyas4991** [teorth/equational_theories#464]
### Describe the bug

The build time on CI has drastically increased to 50 minutes

### To Reproduce
Build a branch that forks off of the current main branch of this project. Run lake build. Build takes more than 1 hour.

### Expected behavior

Build in under 30 minutes on a 32 GB RAM machine. CI runs under 20 minutes.

### Additional Discussion 
  See: https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/slow.20build

**Comment by dwrensha** [comment]
claim

**Comment by dwrensha** [comment]
propose PR #465

**Comment by 0art0** [comment]
Thank you for debugging this. I can find an alternative approach to using environment extensions to keep track of the laws, for example by traversing the environment.

**Comment by dwrensha** [comment]
I may have spoken too soon. `lake build` is now fast, but the documentation build in CI still seems slower than it was two days ago.

**Comment by Shreyas4991** [comment]
The documentation has been taking 10 minutes even with the cache. This doesn't seem to be something we can fix within this project.

**Comment by Shreyas4991** [comment]
two days ago? Hmmm, there was a PR that changed how the documentation was rendered to improve some vscode stuff.
