### ISSUE TITLE
FRONTEND: "Prove this!" gives the opposite implication

### ISSUE THREAD

**Issue by madvorak** [teorth/equational_theories#469]
Go to:
https://teorth.github.io/equational_theories/implications/?359

You will see "Unknown By" and the first item is "Equation65[x = y ◇ (x ◇ (y ◇ x))]".
When you click on "Prove this!" it seems to take me to a template for the opposite implication than it should take me, namely:
```
theorem Equation359_implies_Equation65 (G: Type _) [Magma G] (h: Equation359 G) : Equation65 G := by
  sorry
theorem Equation359_not_implies_Equation65 : ∃ (G: Type) (_: Magma G), Equation359 G ∧ ¬ Equation65 G := by
  sorry
```

**Comment by carlini** [comment]
claim

**Comment by carlini** [comment]
Ahha. Just to confirm, it's *only* the lower right box where you see this (only "unknown by"). All of the forward ones are correct, and the backward proven ones are correct?

**Comment by madvorak** [comment]
I think it is only the bottom right box, but I wasn't testing everything.

**Comment by madvorak** [comment]
Also it seems to me that the button "I'm feeling lucky" always takes me to an actual open problem (never to the flipped one).

**Comment by carlini** [comment]
What do you mean by "flipped" one?

**Comment by madvorak** [comment]
I observed that the button "I'm feeling lucky" always takes me to an actual open problem (never to the "wrong" one).

**Comment by carlini** [comment]
propose PR #473

**Comment by madvorak** [comment]
Ignore my last two messages. I was just confirming that it was all right on the examples I tried.

**Comment by carlini** [comment]
There are several I'm aware of:

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/generate_graphiti_data.rb#L16

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/explore_magma.py#L13

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/find_dual.py#L169

https://github.com/teorth/equational_theories/blob/c27789ec7ea82c2d870080bf8c5bc0ff3af12a51/scripts/generate_equation_implication_js.py#L109

**Comment by carlini** [comment]
Oops I responded with the above message to the wrong place

**Comment by carlini** [comment]
The PR was merged, this issue can be closed. (Not sure why that didn't happen automatically.)

**Comment by madvorak** [comment]
Yes, it works correctly now. Thanks a lot!
