### ISSUE TITLE
Typo fix in Definition 7.1 in asterix.tex

### ISSUE THREAD

**Issue by avi-levy** [teorth/equational_theories#470]
**Describe the bug**
In the definition of a partial solution, the second condition is stated as
```
The function $f$ is a bijection from $E_1 \backslash E_0$ to $E_2 \backslash E_0$.
```
but it becomes apparent from later arguments that the intended second condition is
```
The function $f$ is a bijection from $E_1 \backslash E_0$ to $E_2 \backslash E_1$.
```

**Additional context**
I was directed to file a bug report before posting my PR to fix it.

**Comment by avi-levy** [comment]
claim

**Comment by avi-levy** [comment]
propose #471

**Comment by Chessing234** [comment]
Opened # for the remaining codomain typos in the iteration proof.

**Comment by Chessing234** [comment]
Found a missing \\ in the third-case align block that merges two f' definitions on the live blueprint — PR up.
