### ISSUE TITLE
Fix text shadows in the blueprint theme

### ISSUE THREAD

**Issue by Shreyas4991** [teorth/equational_theories#489]
The new blueprint theme adds shadows to text on the sidebar and navbar. This gives the text a blurry feel which is stressful on the eye (at least for me). The task is to either fix this or choose a theme which doesn't have accessbility issues.

**Comment by Shreyas4991** [comment]
Surely we can modify the CSS to  remove the shadows?

**Comment by vlad902** [comment]
claim

**Comment by vlad902** [comment]
propose PR #646
