### ISSUE TITLE
WORKFLOW: 'claim'ed out of order and got an inconsistent state/confusing error message

### ISSUE THREAD

**Issue by vlad902** [teorth/equational_theories#498]
I think I just hit a slight bug in the workflow. If you take a look at https://github.com/teorth/equational_theories/issues/493 I said "claim" in the second message, before it was assigned to the project so the issue was assigned to me. Terence then added it to the project, I tried 'claim' again and that failed with a slightly confusing error message: https://github.com/teorth/equational_theories/actions/runs/11280485193.

The confusing error is due to the `check_assignee` step in `.github/workflows/01-claim-issue.yml` echoing JSON using double quotes but the JSON contains double quotes so it escapes into the shell context and fails without printing the expected error [also, it exits with exit 0 so I think it may have otherwise succeeded? I don't know if exit code is used to signal success/failure in these workflows or something else.]

I think there's 2 bugs: 1) the poor handling of JSON leading to the confusing error message, and 2) that I could claim the issue before it was part of the project, so now it's stuck in the 'unclaimed' state despite being assigned. Or perhaps I misunderstand the workflow.

cc @pitmonticone

**Comment by pitmonticone** [comment]
Thank you for the feedback @vlad902. 

I'll take a look at it later or tomorrow.

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
disclaim

**Comment by pitmonticone** [comment]
TEST claim TEST

**Comment by pitmonticone** [comment]
disclaim

**Comment by pitmonticone** [comment]
TEST claim TEST

**Comment by pitmonticone** [comment]
Solved the first issue.

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
disclaim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
disclaim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
YES!!!

**Comment by pitmonticone** [comment]
disclaim

**Comment by pitmonticone** [comment]
Removed this issue from the project

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by vlad902** [comment]
This looks related to your current changes: See the output of this run, where it tried to execute the code in backticks: https://github.com/teorth/equational_theories/actions/runs/11282128524/job/31378925062

**Comment by pitmonticone** [comment]
@vlad902 Can you point me to the exact issue? 

I'm a bit busy with inline fragments and other hellish stuff...

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
> This looks related to your current changes: See the output of this run, where it tried to execute the string in backticks included from the github issue title: https://github.com/teorth/equational_theories/actions/runs/11282128524/job/31378925062

@vlad902 Oh I see. That is correct.

**Comment by vlad902** [comment]
> @vlad902 Can you point me to the exact issue?
> 
> I'm a bit busy with inline fragments and other hellish stuff...

This is from that run
```
Run TRIMMED_COMMENT=$(echo "Opened #501 to track `export_equations` breakage." | tr -d '\n' | xargs)
/home/runner/work/_temp/73[9](https://github.com/teorth/equational_theories/actions/runs/11282128524/job/31378925062#step:2:10)db416-5175-4d5c-bd80-11bbc0a2a325.sh: line 1: export_equations: command not found
```

The comment body is being passed in a string, but backticks cause command execution in shells, so it's failing because it tried to run `export_equations`. This potentially allows anyone to inject commands into the github workflow.

**Comment by pitmonticone** [comment]
No no, it doesn't. It was just a past version of the workflow script which didn't contain the correct condition at the beginning. The workflow should not even be triggered there and it wouldn't be in the current state.

**Comment by pitmonticone** [comment]
claim

**Comment by vlad902** [comment]
test claim `exit 0`

**Comment by vlad902** [comment]
test claim `echo 'by injecting commands here, I could presumably grab the secrets.PAT_TOKEN/secrets.GITHUB_TOKEN'`

**Comment by vlad902** [comment]
i could take it further, but i think it demonstrates the bug. Googling around quickly, it seems like instead of using `TRIMMED_COMMENT=...` github workflows support writing data directly to env vars, and then you can do something like `TRIMMED_COMMENT=(echo $COMMENT | ...` that won't be effected by this.

**Comment by pitmonticone** [comment]
I'm sorry but don't understand your point here. Where is the bug?

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
disclaim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by Shreyas4991** [comment]
I think @vlad902 means that you need to escape the input in some way.

**Comment by pitmonticone** [comment]
Yes, I think I've done it via step env.

**Comment by pitmonticone** [comment]
claim

**Comment by Shreyas4991** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
claim
