### ISSUE TITLE
EQUATION_EXPLORER: Fix glitches in the commentary feature

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#507]
When navigating to an equation with a commentary, the standard heading of the equation (listing the equation number, form, and dual) is missing.

When navigating from an equation without commentary to an equation with commentary, the standard heading of the old equation is retained even though the display otherwise switches to the new equation.

When navigating from an equation with commentary to an equation without commentary, the commentary from the previous equation is retained.

(Note: I think the correct functionality should be that an equation page should always display the standard header (including the duality information), and also the commentary if it exists.  At present, the commentary also somewhat duplicates the header information, leading to some redundancy, but I plan to clean up the commentary files to remove this redundancy once this glitch is fixed.

**Comment by vlad902** [comment]
claim

**Comment by vlad902** [comment]
I was able to easily replicate and fix two things: 1) the old commentary not being cleared between page transitions, and 2) the equation number not being displayed for pages with commentary. I found that the dual was always presented though, below the commentary, so I wonder if that was just an oversight or if I'm missing something. Perhaps adding a thin black box around the commentary can visually differentiate it from the rest of elements, e.g.
<img width="1455" alt="Screenshot" src="https://github.com/user-attachments/assets/22081e32-5f6a-47aa-ac4b-97f71fa053e6">

**Comment by vlad902** [comment]
propose PR #522

**Comment by teorth** [comment]
Thanks!

On looking at it further, the issue is that for equations that are self-dual (e.g., equations 1 or 2), no text is provided regarding duality, so I thought they were somehow overwritten.  Perhaps adding a note indicating self-duality on the appropriate equation pages would be good.
