### ISSUE TITLE
REWRITING: Establish all of the remaining anti-implications coming from 2126

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#515]
See https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Equation.202126 for a sketch.  . The tasks are to

* Transfer Equation 2126 from `Eqns2000_2999.lean` to `Equations.lean` (leaving a commented out version in the former file);
* Add Equation 2126 to Chapter 2 of the blueprint;
* Add some version of the proof in the above discussion to a blueprint chapter (either as part of an existing chapter such as the abstract nonsense chapter, or starting a new chapter);
Formalize the statement and proof of the theorem in Lean (in some lean file TBD);
Add the Lean file to the main equational_theories.lean file so that it is compiled by CI; and
Add \lean and \leanok tags to the blueprint version of the proof.

There are 35 other laws that are to be anti-implied by 2126; but it should not be necessary to add them to the blueprint or to Equations.lean as the checking should be rote once the complete rewriting system is set up.  (Thus, the lean files here would import from `All.lean` even after moving 2126 to `Equations.lean`; the reason for the move is to keep the blueprint Chapter 2 and `Equations.lean` aligned.  Alternatively, one can move the 35 equations over to avoid importing from `All.lean` and improve compile times, but then these equations would also have to be added to Chapter 2 of the blueprint.)

**Comment by lyphyser** [comment]
propose #510
