### ISSUE TITLE
COMBINATORIAL: Refute 73 -> 99, 203, 255, 4380

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#516]
See https://teorth.github.io/equational_theories/blueprint/infinite-magma-constructions-chapter.html#greedy-section for a proof.  (An older proof is also available at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/1076.20!.3D.3E.203/near/476382126 .)

Proof can go in the `ManuallyProved` folder.  When done, update `ManuallyProved.lean` and `Conjectures.lean`, and add \lean and \leanok's to the blueprint.

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
propose #915
