### ISSUE TITLE
LOW PRIORITY: Give Magma.op and MagmaLaw.op less similar names

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#525]
See the discussion at https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Magma.2Eop.20vs.20MagmaLaw.2Eop .  There is no immediate conflict, so this is not an urgent issue, but it may be good to propose less similar names for these rather different operations, and refactor at some point.

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
propose #527
