### ISSUE TITLE
FRONTEND: "Anti-Implies" or rather "Not implies"

### ISSUE THREAD

**Issue by madvorak** [teorth/equational_theories#537]
A friend of mine was confused by the wording "Anti-Implies" in the equation explorer. Maybe we should call it "Not implies".

Even more so, "Anti-Implied By" sounds less clear to me than "Not implied by".

**Comment by teorth** [comment]
I guess the grammatically correct options are "Does not imply" for "Anti-implies", and "Not implied by" by "Anti-implied by".

**Comment by madvorak** [comment]
claim

**Comment by madvorak** [comment]
propose #542
