### ISSUE TITLE
ASTERIX: Refute 1491 -> 65 ("Obelix" -> "Asterix")

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#543]
A sketch of a construction is provided [here](https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Oberlix.3A.20joining.20two.20approaches).

The task involves:
* Writing up the proof in the blueprint (presumably in the "Asterix" chapter);
* Stating and formalizing the proof in the `ManuallyProved` folder;
* Updating `ManuallyProved.lean` afterwards;
* Adding `\lean` and `\leanok` tags to the blueprint proof when done.

One could also claim just the first stage of this project if desired, in which case a new task will be issued for formalizing the blueprint.

**Comment by Timeroot** [comment]
claim! :)

**Comment by Timeroot** [comment]
claim

**Comment by Timeroot** [comment]
propose #624
