### ISSUE TITLE
EQUATION_EXPLORER: Allow the "Enter an equation" textbox to also accept equation numbers

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#565]
Thus, the parser would determine whether the input was a number (e.g., 1184) or an equation (e.g., `x = y ◇ ((z ◇ (z ◇ y)) ◇ x)`), and in either case it would navigate to the appropriate page (e.g., https://teorth.github.io/equational_theories/implications/?1184).

**Comment by Joe-McCann** [comment]
claim

**Comment by Joe-McCann** [comment]
propose https://github.com/teorth/equational_theories/pull/625

**Comment by Joe-McCann** [comment]
propose PR https://github.com/teorth/equational_theories/pull/625

**Comment by JoseBrox** [comment]
> Thus, the parser would determine whether the input was a number (e.g., 1184) or an equation (e.g., `x = y ◇ ((z ◇ (z ◇ y)) ◇ x)`), and in either case it would navigate to the appropriate page (e.g., https://teorth.github.io/equational_theories/implications/?1184).

Perhaps it would also be interesting to be able to search by name: Astérix, Obélix, Dupond, Dupont... and maybe also by selected properties, like "Austin".
