### ISSUE TITLE
GREEDY: Resolve all open implications arising from 1648

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#566]
This should follow from the greedy extension method, as per the discussion in https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/1076.20!.3D.3E.203 .  This task splits into several components:

1.  Work out the mathematical details of the method, and write them to the blueprint (presumably [here](https://teorth.github.io/equational_theories/blueprint/greedy-chapter.html)).
2. Formalize the statement and proof of the anti-implications obtained.
3. Mark the relevant statements in the blueprint with `\lean` and `\leanok` components.

One could perform just the initial portion of this task, and then release the claim on the task for someone else to complete it.

**Comment by Command-Master** [comment]
claim

**Comment by teorth** [comment]
I think it is good to have multiple proofs of particularly interesting implications.  It could make for a good comparative study in the paper, for instance.

**Comment by Command-Master** [comment]
This was closed by #678
