### ISSUE TITLE
MODIFIED_BASE_MODEL: Resolve all implications arising from 1659

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#571]
As per the discussion at https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Hard.20problems.20and.20negative.20results , this should be possible using the "modified translation-invariant magma" approach.

**Comment by zaklogician** [comment]
claim

**Comment by zaklogician** [comment]
propose PR #573

**Comment by zaklogician** [comment]
I've written up this construction as an example of a modified translation-invariant magma [here](https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/Hard.20problems.20and.20negative.20results/near/476656060). I intend to expand and edit it into a blueprint section shortly, comments welcome (that will be a separate PR).
