### ISSUE TITLE
Add requirements.txt with package version numbers to assist in creation of Python environments 

### ISSUE THREAD

**Issue by Joe-McCann** [teorth/equational_theories#572]
When working with Python scripts it is best practice to use a `requirements.txt` file so that all packages can be placed into one location and installed at once. As such a new user would be able to install all requirements through the use of one command
```
pip3 install -r requirements.txt
```
This also freezes packages into a consistent version that ensures that should the package be updated to a new, non-compatible version that our scripts will still work as intended. 

Documentation within the requirements file will also specify how to use it to install for users unaware with python package management practices

**Comment by Joe-McCann** [comment]
claim

**Comment by Shreyas4991** [comment]
project-task

**Comment by Joe-McCann** [comment]
claim

**Comment by Joe-McCann** [comment]
propose PR #580
