### ISSUE TITLE
Shorten the anti-implications proofs of 1701 into a single theorem

### ISSUE THREAD

**Issue by Shreyas4991** [teorth/equational_theories#586]
There are 9-10 anti-implications of equation 1701 [starting here](https://github.com/teorth/equational_theories/blob/6fa72b34a6ec989e2f91589b4d133ae8663f300c/equational_theories/ManuallyProved/Equation1701.lean#L132). Their proofs are nearly identical. They can be compressed into one theorem using the Facts Syntax. For example [see how the anti-implications of equation 1648 are proved](https://github.com/teorth/equational_theories/blob/6fa72b34a6ec989e2f91589b4d133ae8663f300c/equational_theories/ManuallyProved/Equation1648.lean#L32). The task is to use `FactsSyntax` to prove these anti-implications of 1701 in a single theorem instead of a number of separate theorems.

**Comment by madvorak** [comment]
claim

**Comment by madvorak** [comment]
propose #603
