### ISSUE TITLE
REGULAR_TREE: Formalize the tree-based proof that 206 anti-implies 1648

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#596]
Details in https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/1648.20!.3D.3E.20206/near/476985846 .  This anti-implication will also be established by greedy algorithm methods, but the construction is visually appealing and may generalize to other equations.

The proof should go in the `ManuallyProved` section.

**Comment by nomeata** [comment]
claim

**Comment by nomeata** [comment]
propose #599
