### ISSUE TITLE
Equation Explorer didn't update after #599 / shows wrong status

### ISSUE THREAD

**Issue by vlad902** [teorth/equational_theories#604]
https://teorth.github.io/equational_theories/implications/?206 still shows 1648 as a conjecture. The entry in `lake exe extract_implications outcomes` is marked `implicit_conjecture_false`.

**Comment by vlad902** [comment]
After much confusing debugging, it's because #599 has a typo, it proves the refutation of 1684 not 1648.

**Comment by vlad902** [comment]
cc @nomeata I took a brief long at fixing it but you use more advanced features of Lean than I am familiar with and I don't think I can offer much.

**Comment by teorth** [comment]
One side effect of having the security blanket of Lean verification for the formal side of the project is that one tends to get a bit more disconcerted about errors showing up in the informal side of the project...
