### ISSUE TITLE
DASHBOARD: Enhance the dashboard to include links to various formats of the implication table

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#631]
For instance, links could be made to compressed JSON or CSV versions of the table, generated automatically during CI (possibly only once a day, for instance, if compilation time is excessive).  The individual entries of the dashboad table could also be linked to custom files; for instance, the "explicitly true" entry could link to a file of explicitly true implications, in some suitable format (e.g., JSON or raw text).

Iniitally proposed in the comments to #626.

**Comment by vlad902** [comment]
claim

**Comment by vlad902** [comment]
propose PR #973

**Comment by vlad902** [comment]
I forgot to link this, this can now be closed.
