### ISSUE TITLE
MODIFIED_GREEDY: Refute 879 -> 4065

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#633]
See [this discussion](https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Equation.20879.20!.3D.3E.204065) for the proof.  

The formal proof can go in the `ManuallyProved` folder. `ManuallyProved.lean` should be updated afterwards, and the appropriate conjectures from `Conjectures.lean` removed.

**Comment by amirlb** [comment]
propose #830

**Comment by teorth** [comment]
Closed by #941
