### ISSUE TITLE
GREEDY: Refute 63 "Dupont" ->1692 "Dupond"

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#643]
The proof can be found in https://teorth.github.io/equational_theories/blueprint/infinite-magma-constructions-chapter.html#dupont-section .  See also https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Proposed.20new.20target.3A.2063.20and.201692.20.28.22Dupont.20and.20Dupond.22.29 for more discussion.

An alternate approach is also available at https://teorth.github.io/equational_theories/blueprint/infinite-magma-constructions-chapter.html#greedy-section

The proof can go into the `ManuallyProved` folder.  `ManuallyProved.lean` should be updated afterwards, and the appropriate conjectures from `Conjectures.lean` removed.

**Comment by teorth** [comment]
An alterate treatment of 63 can be found in https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/713.2C.201289.2C.201447/near/482011293.2E01

**Comment by amirlb** [comment]
claim

**Comment by amirlb** [comment]
propose #945
