### ISSUE TITLE
FRONTEND: link (Tools -> Finite Magma Explorer) does not work

### ISSUE THREAD

**Issue by madvorak** [teorth/equational_theories#653]
https://github.com/teorth/equational_theories/tree/main/tools
Tools -> Finite Magma Explorer

**Comment by teorth** [comment]
On which page is this broken link found?  I'm not aware of any "Tools" dropdown list.

**Comment by madvorak** [comment]
I apologize I was not specific enough. It is in this folder:
https://github.com/teorth/equational_theories/tree/main/tools

**Comment by teorth** [comment]
fixed in #655 (hopefully).

**Comment by madvorak** [comment]
Yes, it works now.
