### ISSUE TITLE
GREEDY: Refute 1722 -> 644, 3050, 1832

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#659]
Proof available in blueprint at https://teorth.github.io/equational_theories/blueprint/infinite-magma-constructions-chapter.html#greedy-section

The formalized proof may be placed in the ManuallyProved folder. ManuallyProved.lean should be updated afterwards, and the appropriate conjectures from `Conjectures.lean` removed, and \lean and \leanok's added to the blueprint.

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
disclaim

**Comment by teorth** [comment]
Alternate proof (avoiding translation invariant formalism) at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/713.2C.201289.2C.201447/near/482084613.2E01

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
Partial result using translation invariant approach at #860, but none of the one-variable laws

**Comment by b-reinke** [comment]
disclaim

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
propose #925
