### ISSUE TITLE
GREEDY: Refute 1518 -> 47, 614, 817, 3862

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#661]
A proof may be found at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/478083079

The formalized proof may be placed in the ManuallyProved folder. ManuallyProved.lean should be updated afterwards, and the appropriate conjectures from `Conjectures.lean` removed.

**Comment by teorth** [comment]
Informally claimed by Bernhard Reinke, see above link

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
propose #849
