### ISSUE TITLE
AD_HOC: Resolve all anti-implications from 3342

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#662]
Proof is in #677 and will land in blueprint shortly.

The formal proof can go in `ManuallyProved`.  When done, mark the blueprint theorem with \lean and \leanok statements.

**Comment by teorth** [comment]
This is a relatively simple equation, however it is known that pure translation-invariant approaches do not work; see above link.

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose PR #682
