### ISSUE TITLE
GREEDY: Refute 1526 -> 1223, 2744

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#663]
[A proof may be found at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/477860423](https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/478046392)

The formalized proof may be placed in the ManuallyProved folder. ManuallyProved.lean should be updated afterwards, and the appropriate conjectures from `Conjectures.lean` removed.

**Comment by teorth** [comment]
An alternate version of the argument, avoiding the translation invariant ansatz, can be found at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/713.2C.201289.2C.201447/near/482073351.2E01

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
propose #852
