### ISSUE TITLE
GREEDY: Refute 3308 -> 3456

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#666]
Proof sketch can be found at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/477846456

Proof can go in the `ManuallyProved` folder. `ManuallyProved.lean` should be updated afterwards, and the appropriate conjectures from `Conjectures.lean` removed.

**Comment by teorth** [comment]
Informally claimed by Pace Nielsen, see above link

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
propose #906
