### ISSUE TITLE
MATH: Analyze 1323 -> 2744

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#667]
Findings can be reported at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1

**Comment by teorth** [comment]
Has a similar difficulty to "Ramanujan" (1729) in that the implication is true whenever squaring is surjective, and hence true for all translation invariant models.  See above link.

**Comment by b-reinke** [comment]
claim

**Comment by teorth** [comment]
Now converted to a Zulip thread https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/1323
