### ISSUE TITLE
FINITE: Refute 3352 -> 4065

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#668]
One can use the finite magma stated in https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/478066872

Instructions are as follows:

This magma refutes 1 previously unknown potential implications! Create a PR. Add the following code to plan.txt in `All4x4Tables/data`:
Magma [[1,4,2,2,1,6,0,0],[2,3,2,4,3,6,1,1],[2,2,2,2,2,2,2,2],[4,2,2,0,0,6,3,3],[0,1,2,3,5,6,5,6],[4,4,2,4,6,4,4,6],[1,3,2,0,5,4,7,6],[1,3,2,0,6,6,6,6]]
Satisfies [3352]
Refutes [4065]
Then add the following to extra.txt in `All4x4Tables/data`:
Table [[1,4,2,2,1,6,0,0],[2,3,2,4,3,6,1,1],[2,2,2,2,2,2,2,2],[4,2,2,0,0,6,3,3],[0,1,2,3,5,6,5,6],[4,4,2,4,6,4,4,6],[1,3,2,0,5,4,7,6],[1,3,2,0,6,6,6,6]]
Proves [1,3253,3352]
Finally, re-run `python3 generate-lean.py`!

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose PR #721
