### ISSUE TITLE
FINITE: Refute 3475 -> 3659

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#669]
This amounts to uploading the finite magma in https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/478317056

The instructions are:

Create a PR. Add the following code to plan.txt in `All4x4Tables/data`:
Magma [[2,3,4,6,2,6,4,4,2],[4,2,4,5,2,3,0,7,2],[8,8,3,3,3,0,1,2,5],[8,8,2,3,7,0,1,2,5],[8,8,7,2,3,0,1,3,5],[2,4,4,7,2,2,3,4,6],[3,2,4,7,2,4,2,4,4],[8,8,3,2,7,0,1,3,5],[1,5,4,7,2,2,3,7,2]]
Satisfies [3475]
Refutes [3659]
Then add the following to extra.txt in `All4x4Tables/data`:
Table [[2,3,4,6,2,6,4,4,2],[4,2,4,5,2,3,0,7,2],[8,8,3,3,3,0,1,2,5],[8,8,2,3,7,0,1,2,5],[8,8,7,2,3,0,1,3,5],[2,4,4,7,2,2,3,4,6],[3,2,4,7,2,4,2,4,4],[8,8,3,2,7,0,1,3,5],[1,5,4,7,2,2,3,7,2]]
Proves [1,3456,3475]
Finally, re-run `python3 generate-lean.py`!

**Comment by teorth** [comment]
claim

**Comment by teorth** [comment]
disclaim

**Comment by teorth** [comment]
Analysis appears in https://github.com/teorth/equational_theories/pull/685 and also https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/477917205 .

**Comment by Command-Master** [comment]
disclaim

**Comment by teorth** [comment]
Closed by #717
