### ISSUE TITLE
GREEDY: Refute 1516 ->1489

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#675]
A proof may be found at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/477860423

The formalized proof may be placed in the `ManuallyProved` folder. `ManuallyProved.lean` should be updated afterwards and the appropriate conjectures from `Conjectures.lean` should be removed.

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
propose #831
