### ISSUE TITLE
AD_HOC: Formalize the proof of 1437 !=> 4269

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#690]
Proof is in https://teorth.github.io/equational_theories/blueprint/infinite-magma-constructions-chapter.html#adhoc-model and also #688.  

Formalization can go in the `ManuallyProved` folder. `ManuallyProved.lean` should be updated afterwards.

When done, mark the relevant blueprint theorem with \lean and \leanok tags.

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose PR #696
