### ISSUE TITLE
LINEAR: Formalize the proof of 1117 !=> 2441

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#691]
Proof is outlined at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/477928995.2E01 .

Formalization can go in the `ManuallyProved` folder.  `ManuallyProved.lean` should be updated afterwards.

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose PR #695
