### ISSUE TITLE
FINITE: Refute 854 -> 107,1248,1251

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#701]
One can use the finite magma from https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Outstanding.20equations.2C.20v1/near/478094170

Instructions are as follows:
Create a PR. Add the following code to plan.txt in `All4x4Tables/data`:
Magma [[5,11,3,5,0,0,11,6,0,0,11,6],[4,2,1,4,1,1,4,1,1,1,4,1],[2,2,7,2,8,4,4,2,4,8,2,8],[5,11,3,5,3,3,11,1,3,3,11,1],[4,4,7,4,7,4,4,4,4,8,4,8],[5,5,7,5,5,4,4,5,10,5,5,5],[5,5,10,5,6,10,4,6,10,6,5,6],[9,7,7,9,7,7,7,1,7,7,7,8],[8,8,7,8,8,4,4,8,10,8,8,8],[9,9,7,9,7,9,9,9,9,8,9,8],[9,4,10,4,10,10,9,10,10,10,4,10],[9,11,7,9,7,11,11,9,11,7,11,8]]
Satisfies [854]
Refutes [107,1248,1251]
Then add the following to extra.txt in `All4x4Tables/data`:
Table [[5,11,3,5,0,0,11,6,0,0,11,6],[4,2,1,4,1,1,4,1,1,1,4,1],[2,2,7,2,8,4,4,2,4,8,2,8],[5,11,3,5,3,3,11,1,3,3,11,1],[4,4,7,4,7,4,4,4,4,8,4,8],[5,5,7,5,5,4,4,5,10,5,5,5],[5,5,10,5,6,10,4,6,10,6,5,6],[9,7,7,9,7,7,7,1,7,7,7,8],[8,8,7,8,8,4,4,8,10,8,8,8],[9,9,7,9,7,9,9,9,9,8,9,8],[9,4,10,4,10,10,9,10,10,10,4,10],[9,11,7,9,7,11,11,9,11,7,11,8]]
Proves [1,8,99,101,359,378,411,413,430,817,818,823,832,843,854,1020,1022,1025,1028,1031,1035,1045,1055,1223,1225,1228,1231,1234,1241,1832,3253,3255,3316,3319,3862,3867,3915,3925,4065,4131]
Finally, re-run `python3 generate-lean.py`!

**Comment by Command-Master** [comment]
claim

**Comment by Command-Master** [comment]
propose PR #721
