### ISSUE TITLE
Correct Equation 5105 numbering

### ISSUE THREAD

**Issue by vlad902** [teorth/equational_theories#714]
As I noted [here](https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Equation.205105.20-.3E.20Equation.202/near/478252043), I believe Equation 5105 is actually 5093. This claim should be double-checked and then it should be renumbered everywhere (blueprint, src, etc.)

**Comment by teorth** [comment]
claim

**Comment by teorth** [comment]
propose PR #715
