### ISSUE TITLE
TOOL: code to compute the equation number of the dual of an equation

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#72]
Example: Equation4564 is `x ∘ (y ∘ z) = (w ∘ y) ∘ z`.  Reversing all operations gives `(z ∘ y) ∘ = z ∘ (y ∘ w)`, which after relabeling and symmetry is Equation 4513, `x ∘ (y ∘ z) = (x ∘ y) ∘ w`.  Thus 4564 and 4513 are duals.  A code to output the dual of any given equation, and/or a table of equations and their duals, would be useful for the project.

**Comment by carlini** [comment]
I think I have a tool that does this, but in another issue (#77) you write "Note that 4378 is dual to 4522, so one should be able to adapt the proofs of several implications."

But
`equation 4378 := x ∘ (y ∘ z) = w ∘ (u ∘ z)`
and
`equation 4522 := x ∘ (y ∘ z) = (x ∘ w) ∘ u`

which doesn't match my understanding of dual as you've written it here, because if you flip the first you get `(z ∘ y) ∘ x = (z ∘ u) ∘ w` which doesn't structurally match the second  `x ∘ (y ∘ z) = (x ∘ w) ∘ u`.

**Comment by teorth** [comment]
Oops, you are right, 4522 is dual to 4579, not 4378.  Will fix this ASAP.

**Comment by carlini** [comment]
If my understanding is right, there are 2305 equations with a corresponding dual which is 98.2%. Here are some duals

| Equation | Dual |
| ----- | ----- |
| Equation5[(x = (y ∘ x))] | Equation4[(x = (x ∘ y))] |
| Equation23[(x = ((x ∘ x) ∘ x))] | Equation8[(x = (x ∘ (x ∘ x)))] |
| Equation24[(x = ((x ∘ x) ∘ y))] | Equation13[(x = (y ∘ (x ∘ x)))] |
| Equation25[(x = ((x ∘ y) ∘ x))] | Equation10[(x = (x ∘ (y ∘ x)))] |
| Equation26[(x = ((x ∘ y) ∘ y))] | Equation16[(x = (y ∘ (y ∘ x)))] |
| Equation27[(x = ((x ∘ y) ∘ z))] | Equation19[(x = (y ∘ (z ∘ x)))] |
| Equation28[(x = ((y ∘ x) ∘ x))] | Equation9[(x = (x ∘ (x ∘ y)))] |
| Equation29[(x = ((y ∘ x) ∘ y))] | Equation14[(x = (y ∘ (x ∘ y)))] |
| ... | ... |
| Equation4690[(((x ∘ y) ∘ z) = ((w ∘ y) ∘ u))] | Equation4375[((x ∘ (y ∘ z)) = (w ∘ (y ∘ u)))] |
| Equation4691[(((x ∘ y) ∘ z) = ((w ∘ z) ∘ y))] | Equation4363[((x ∘ (y ∘ z)) = (y ∘ (x ∘ w)))] |
| Equation4692[(((x ∘ y) ∘ z) = ((w ∘ z) ∘ u))] | Equation4368[((x ∘ (y ∘ z)) = (y ∘ (w ∘ u)))] |
| Equation4693[(((x ∘ y) ∘ z) = ((w ∘ u) ∘ z))] | Equation4361[((x ∘ (y ∘ z)) = (x ∘ (w ∘ u)))] |
| Equation4694[(((x ∘ y) ∘ z) = ((w ∘ u) ∘ v))] | Equation4379[((x ∘ (y ∘ z)) = (w ∘ (u ∘ v)))] |

I'll add the script that generates this, where should I dump the full output table? (I'll probably also list the 84 equations that have no dual.

**Comment by teorth** [comment]
Hmm, I guess we can create a top-level `data` directory for this sort of thing (it could also go in `scripts`, but perhaps it is conceptually better to separate the code from the data it generates
