### ISSUE TITLE
ALGORITHMIC: An algorithm that takes an arbitrary equation of any length and returns its number, or vice versa, in reasonable time

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#724]
The existing scripts to generate equations and find their ids works well enough for equations of length up to 6, but become computationally difficult beyond that.   In principle, the recursive formulae at https://oeis.org/A376640 , https://oeis.org/A376620, https://oeis.org/A103293 may help.  See the discussion at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Reconstructing.20the.204694.20expressions.20from.20the.20ground.20up.2E

**Comment by blefloch** [comment]
Is it ok to only produce a python script like [find_equation_id.py](https://github.com/teorth/equational_theories/blob/main/scripts/find_equation_id.py), with the risk of mistakes (especially with the subtle symmetry issues for even n) or should it be Lean code with a proof of correctness?

**Comment by teorth** [comment]
I think at this stage a python script would be sufficient, as currently the Lean project only treats individual extended equations rather than the whole class of extended equations.

**Comment by blefloch** [comment]
Ok, I'd like to claim this issue.  I now have code that works for odd numbers of operations.  For instance, it reaches without trouble such monsters as
```
Equation 1000000000: x = y ◇ ((z ◇ (x ◇ (((w ◇ y) ◇ (u ◇ (u ◇ w))) ◇ u))) ◇ z)
Equation 1000000000000: x = (((y ◇ (z ◇ (z ◇ y))) ◇ w) ◇ (x ◇ y)) ◇ (((z ◇ u) ◇ (v ◇ r)) ◇ u)
Equation 1000000000000000000000000: x ◇ y = (x ◇ (x ◇ ((z ◇ (((w ◇ ((u ◇ w) ◇ v)) ◇ u) ◇ r)) ◇ x))) ◇ ((((v ◇ (((s ◇ u) ◇ z) ◇ (r ◇ w))) ◇ x) ◇ z) ◇ r)
```
For even numbers of operations I have to carefully determine how symmetry interacts with the ordering, but I think it is doable.

**Comment by teorth** [comment]
OK, great! Can you post a single "claim" comment to make it official?

**Comment by blefloch** [comment]
claim

**Comment by blefloch** [comment]
propose #833

**Comment by blefloch** [comment]
awaiting-review
