### ISSUE TITLE
GRAPH_GREEDY: Refute 1485 -> 3457, 2124, 2087, 3511

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#737]
Proof is in the "weak central groupoid" chapter of blueprint, uploaded in #735.

When done, add \lean and \leanok tags to the appropriate theorems. Feel free to refactor the blueprint proof (and add \uses tags) as appropriate.

**Comment by digama0** [comment]
claim

**Comment by digama0** [comment]
propose #738

**Comment by teorth** [comment]
Moving this back to "claimed tasks" since there is still work to be done (and Mario is working on it).

**Comment by digama0** [comment]
propose #744
