### ISSUE TITLE
SUBGRAPH: Prove 39 and 45 are equivalent

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#74]
This is dual to the existing equivalence of 38 and 42.

**Comment by Shiney** [comment]
claim

**Comment by Shiney** [comment]
propose PR #86

**Comment by Shreyas4991** [comment]
@pitmonticone the propose action doesn seem to have worked here. I'll manually add it.

**Comment by Shiney** [comment]
@Shreyas4991  wasn't it already linked because I added it as a comment to the PR?

**Comment by Shreyas4991** [comment]
It should have been, but much like the rest of the project, the use of automation for this style of task management is an ongoing experiment. Sometimes the CI action doesn't kick in and we have to debug the cause.  It is for this reason that I have noted in the contribution doc that we are stepping in to handle these tasks manually from time to time
