### ISSUE TITLE
LARGE GREEDY or GREEDY: Refute 713 -> 817, 1426, 3862, 4065

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#771]
As discussed in https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/1076.20!.3D.3E.203/near/476933251 , we have in principle a formalized proof of these implications, but they are extremely large.

See further discussion at
https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Remaining.20unformalized.20theorems.3F/near/479985776 and https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/713.2C.201289.2C.201447

Proof can go in the `ManuallyProved` folder.  When done, update `ManuallyProved.lean`, `Conjectures.lean` and add \lean and \leanok's to the blueprint.

**Comment by teorth** [comment]
Alternate proof of 713: https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/713.2C.201289.2C.201447/near/482096595

Alternate proof of 1289; https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/713.2C.201289.2C.201447/near/481758653

Alternate proof of 1447: https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/713.2C.201289.2C.201447/near/482236139

**Comment by b-reinke** [comment]
claim

**Comment by b-reinke** [comment]
propose #939
