### ISSUE TITLE
FINITE_IMPLICATIONS: Prove Lemmas 3.7 and 3.8

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#809]
[Lemma 3.7](https://teorth.github.io/equational_theories/blueprint/infinite-model-chapter.html#ffg) and [Lemma 3.8](https://teorth.github.io/equational_theories/blueprint/infinite-model-chapter.html#gff) are lemmas about functions on finite sets that can prove implications in finite magmas, see https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Austin.20pairs/near/480601897

When done, place \lean and \leanok tags in the blueprint accordingly.

**Comment by vlad902** [comment]
claim

**Comment by vlad902** [comment]
propose PR #931
