### ISSUE TITLE
WRITING: Organize the greedy arguments in Section 7.4 of the blueprint

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#902]
Discussed [here](https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Drafting.20the.20paper/near/484105069).  The aim is to make the outstanding implications easier to systematically formalize.  The text in this section may also form the base of Section 5.5 of the paper.

**Comment by mjtb49** [comment]
claim

**Comment by mjtb49** [comment]
propose PR #912
