### ISSUE TITLE
WRITING: Write a section or blueprint chapter on the order 5 trivial/Austin laws

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#923]
Report on the outcomes discussed at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Some.20results.20from.20order.205

Some of the text may need to be placeholders since this is still work in progress.

Given that the partial nature of the results, it may  be more appropriate to write up the results in a blueprint chapter.  See the discussion at https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Drafting.20the.20paper/near/488717953

**Comment by vlad902** [comment]
claim

**Comment by teorth** [comment]
closed by #1027
