### ISSUE TITLE
FINITE: Prove 906 -> 3862 for finite magmas

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#934]
Informal proof can be found in https://teorth.github.io/equational_theories/blueprint/906-chapter.html or https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Austin.20pairs/near/484653207 .  Formal proof can go in the `ManuallyProved` folder.  When done, update `ManuallyProved.lean` and `Conjectures.lean`, and add `\lean` and `\leanok` to the blueprint as appropriate.

**Comment by vlad902** [comment]
claim

**Comment by vlad902** [comment]
propose PR #962
