### ISSUE TITLE
FINITE: Establish 1441->4067, 1443->3055, 1681->3877, 1701->1035

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#986]
Turn the conjectures to theorems in

https://github.com/teorth/equational_theories/blob/main/equational_theories/ManuallyProved/Equation1441.lean

using the proofs provided in the blueprint

When done, add `\lean` and `\leanok` tags to the blueprint as appropriate.

**Comment by vlad902** [comment]
propose PR #1015
